version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven"
      - yum install -y maven

  build:
    commands:
      - echo "Build started"
      - cd backend
      - mvn clean package

artifacts:
  files:
    - backend/target/*.jar   ✅ IMPORTANT FIX