CREATE TABLE car (
    id INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1)
        PRIMARY KEY,
    name VARCHAR(100),
    brand VARCHAR(100),
    price DECIMAL(10,2),
    image VARCHAR(255)
);

CREATE TABLE users (
 id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 name VARCHAR(100),
 email VARCHAR(100),
 password VARCHAR(100)
);